package route_info

import (
	"fmt"
	"path/filepath"
	"reflect"
	"slices"
	"sort"
	"strings"
	"unicode"
)

const tsLintIgnore = `/* eslint-disable */
/* oxlint-disable */
// @ts-nocheck
`

// GenerateTypeScript renders a deterministic, endpoint-oriented TypeScript
// contract as a single self-contained file (includes ApiResponse).
//
// Deprecated in favor of GenerateTypeScriptFiles; kept for the --output
// single-file mode (output path ending in .ts).
func GenerateTypeScript(routes *ProjectRoutes) string {
	var b strings.Builder
	b.WriteString("// Code generated by nr route-info gen-ts. DO NOT EDIT.\n")
	b.WriteString(tsLintIgnore)
	b.WriteString("\n")
	b.WriteString("export interface ApiResponse<T> {\n  code: number\n  msg: string\n  data: T\n}\n\n")

	items := slices.Clone(routes.Routes)
	slices.SortFunc(items, func(a, b RouteInfo) int {
		return strings.Compare(a.Method+" "+a.FullPath, b.Method+" "+b.FullPath)
	})
	used := make(map[string]int)
	for _, route := range items {
		name := uniqueTypePrefix(route, used)
		writeRouteTypes(&b, route, name)
	}
	return b.String()
}

// GenerateTypeScriptFiles renders one .gen.ts file per route source file.
// It returns a map of relative output path → file content:
//
//	_common.gen.ts           shared ApiResponse<T> wrapper
//	category.gen.ts          from internal/routes/v1/category_routes.go
//	user.gen.ts              from internal/routes/app/user_routes.go
//
// Per-file contracts import ApiResponse from _common.gen.ts. This layout lets
// a project delete hand-written request/response types per module and keep
// hand-written files (models, helpers) next to the generated ones.
func GenerateTypeScriptFiles(routes *ProjectRoutes) map[string]string {
	byFile := map[string][]RouteInfo{}
	for _, r := range routes.Routes {
		byFile[r.File] = append(byFile[r.File], r)
	}

	srcFiles := make([]string, 0, len(byFile))
	for src := range byFile {
		srcFiles = append(srcFiles, src)
	}
	sort.Strings(srcFiles)

	out := map[string]string{}
	out["_common.gen.ts"] = "// Code generated by nr route-info gen-ts. DO NOT EDIT.\n" +
		tsLintIgnore + "\n" +
		"export interface ApiResponse<T> {\n  code: number\n  msg: string\n  data: T\n}\n"

	for _, src := range srcFiles {
		var b strings.Builder
		b.WriteString("// Code generated by nr route-info gen-ts. DO NOT EDIT.\n")
		b.WriteString(tsLintIgnore)
		b.WriteString("// Source: " + src + "\n\n")
		b.WriteString("import type { ApiResponse } from './_common.gen.ts'\n\n")

		routes := byFile[src]
		slices.SortFunc(routes, func(a, b RouteInfo) int {
			return strings.Compare(a.Method+" "+a.FullPath, b.Method+" "+b.FullPath)
		})
		used := make(map[string]int)
		for _, route := range routes {
			name := uniqueTypePrefix(route, used)
			writeRouteTypes(&b, route, name)
		}
		out[tsGenBaseName(src)+".gen.ts"] = b.String()
	}
	return out
}

// tsGenBaseName derives the .gen.ts file base name from a Go route source
// path: category_routes.go → category, app_routes.go → app, routes.go → api.
func tsGenBaseName(src string) string {
	base := filepath.Base(src)
	base = strings.TrimSuffix(base, ".go")
	base = strings.TrimSuffix(base, "_routes")
	if base == "" || base == "routes" {
		base = "api"
	}
	return base
}

func uniqueTypePrefix(route RouteInfo, used map[string]int) string {
	base := toPascal(route.Method + " " + route.FullPath)
	used[base]++
	if used[base] == 1 {
		return base
	}
	return fmt.Sprintf("%s%d", base, used[base])
}

func toPascal(value string) string {
	var b strings.Builder
	upperNext := true
	for _, r := range value {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if upperNext {
				b.WriteRune(unicode.ToUpper(r))
				upperNext = false
				continue
			}
			b.WriteRune(unicode.ToLower(r))
			continue
		}
		upperNext = true
	}
	return b.String()
}

func writeRouteTypes(b *strings.Builder, route RouteInfo, name string) {
	for _, param := range route.Params {
		fields := param.Fields
		if len(fields) == 0 {
			continue
		}
		suffix := requestSuffix(route, param)
		writeInterface(b, name+suffix, fields, true)
	}

	dataType := "null"
	if len(route.Returns) > 0 {
		ret := route.Returns[0]
		dataType = writeResponseDataType(b, name, ret)
	}
	b.WriteString(fmt.Sprintf("export type %sResponse = ApiResponse<%s>\n\n", name, dataType))
}

func writeResponseDataType(b *strings.Builder, name string, ret ReturnInfo) string {
	// core.ListResponse[T] — paginated list wrapper: data: { list: T[]; total }
	if ret.ListElementType != "" {
		elemType := tsType(ret.ListElementType, ret.ListElementFields)
		return fmt.Sprintf("{ list: Array<%s>; total: number }", elemType)
	}
	if len(ret.Fields) == 0 {
		return tsType(ret.Type, nil)
	}
	base := strings.TrimLeft(ret.Type, "*")
	if strings.HasPrefix(base, "[]") {
		itemName := name + "ResponseItem"
		writeInterface(b, itemName, ret.Fields, false)
		return "Array<" + itemName + ">"
	}
	dataName := name + "ResponseData"
	writeInterface(b, dataName, ret.Fields, false)
	return dataName
}

func requestSuffix(route RouteInfo, param ParamInfo) string {
	switch param.Source {
	case "body":
		return "Body"
	case "query":
		return "Query"
	case "uri":
		return "Path"
	case "request":
		// RequestE binds JSON or form depending on content type. Structs that
		// carry form tags are query-style (used by GET list endpoints and
		// POST actions that take query params); the rest are JSON bodies.
		if route.Method == "GET" || route.Method == "DELETE" || hasFormTag(param.Fields) {
			return "Query"
		}
		return "Body"
	default:
		return "Params"
	}
}

func hasFormTag(fields []FieldInfo) bool {
	for _, f := range fields {
		name := reflect.StructTag(f.Tag).Get("form")
		// form:"-" explicitly opts out of binding and never makes a struct
		// query-style (e.g. LoginParams.Verify json:"-" form:"-").
		if name != "" && name != "-" {
			return true
		}
	}
	return false
}

func writeInterface(b *strings.Builder, name string, fields []FieldInfo, request bool) {
	b.WriteString(fmt.Sprintf("export interface %s {\n", name))
	for _, field := range fields {
		fieldName, include := tsFieldName(field, request)
		if !include {
			continue
		}
		// Request fields are optional unless the backend enforces
		// binding:"required" — omitting a non-required field binds its zero
		// value instead of failing. Response fields are optional when the
		// backend can omit them (omitempty or pointer). Ent-generated models
		// use omitempty by default, so it does not express API optionality.
		optional := fieldRequired(field)
		if request {
			optional = !optional
		} else {
			optional = !optional && (strings.HasPrefix(field.Type, "*") || (!field.FromEnt && hasOmitEmpty(field.Tag)))
		}
		marker := ""
		if optional {
			marker = "?"
		}
		b.WriteString(fmt.Sprintf("  %s%s: %s\n", tsPropertyName(fieldName), marker, tsType(field.Type, field.Fields)))
	}
	b.WriteString("}\n\n")
}

func tsFieldName(field FieldInfo, request bool) (string, bool) {
	key := "json"
	if request {
		key = "form"
	}
	name := reflect.StructTag(field.Tag).Get(key)
	if name == "" && request {
		name = reflect.StructTag(field.Tag).Get("json")
	}
	if name != "" {
		name = strings.Split(name, ",")[0]
	}
	if name == "-" {
		return "", false
	}
	if name == "" {
		name = field.Name
	}
	return name, true
}

func jsonHasOption(tag, option string) bool {
	parts := strings.Split(reflect.StructTag(tag).Get("json"), ",")
	return slices.Contains(parts[1:], option)
}

// hasOmitEmpty reports whether any binding tag on the field carries omitempty
// (pointer types are handled separately at the call site).
func hasOmitEmpty(tag string) bool {
	for _, key := range []string{"json", "form", "uri"} {
		parts := strings.Split(reflect.StructTag(tag).Get(key), ",")
		if slices.Contains(parts[1:], "omitempty") {
			return true
		}
	}
	return false
}

func fieldRequired(field FieldInfo) bool {
	if field.Required {
		return true
	}
	for rule := range strings.SplitSeq(reflect.StructTag(field.Tag).Get("binding"), ",") {
		if strings.TrimSpace(rule) == "required" {
			return true
		}
	}
	return false
}

func tsPropertyName(name string) string {
	if name == "" {
		return "unknown"
	}
	for _, r := range name {
		if !(unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' || r == '$') {
			return fmt.Sprintf("%q", name)
		}
	}
	return name
}

func tsType(goType string, fields []FieldInfo) string {
	base := strings.TrimSpace(goType)
	nullable := false
	for strings.HasPrefix(base, "*") {
		nullable = true
		base = strings.TrimPrefix(base, "*")
	}

	var result string
	switch {
	case strings.HasPrefix(base, "[]"):
		result = "Array<" + tsType(strings.TrimPrefix(base, "[]"), fields) + ">"
	case strings.HasPrefix(base, "map[") || base == "gin.H":
		result = "Record<string, unknown>"
	case len(fields) > 0:
		result = tsInlineObject(fields)
	case base == "string" || base == "rune" || base == "byte" || base == "time.Time":
		result = "string"
	case isNumberType(base):
		result = "number"
	case base == "bool":
		result = "boolean"
	case base == "interface{}" || base == "any":
		result = "unknown"
	case strings.HasSuffix(base, "EmptyResponse"):
		result = "null"
	default:
		result = "unknown"
	}
	if nullable && result != "null" {
		return result + " | null"
	}
	return result
}

func tsInlineObject(fields []FieldInfo) string {
	var b strings.Builder
	b.WriteString("{ ")
	for i, field := range fields {
		if i > 0 {
			b.WriteString(" ")
		}
		name, include := tsFieldName(field, false)
		if !include {
			continue
		}
		marker := ""
		if hasOmitEmpty(field.Tag) || strings.HasPrefix(field.Type, "*") {
			marker = "?"
		}
		b.WriteString(fmt.Sprintf("%s%s: %s;", tsPropertyName(name), marker, tsType(field.Type, field.Fields)))
	}
	b.WriteString(" }")
	return b.String()
}

func isNumberType(value string) bool {
	switch value {
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
		return true
	default:
		return false
	}
}
