package wire2loom

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// fixture is a miniature Wire project laid out the way neter generates them.
func fixture(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	files := map[string]string{
		"go.mod": "module example.com/app\n\ngo 1.25.0\n\nrequire github.com/google/wire v0.5.0\n",
		"pkg/logger/provider.go": `package logger

import "github.com/google/wire"

var ProviderLoggerSet = wire.NewSet(
	NewLoggerWithBroadcaster,
	NewLogBroadcaster,
)
`,
		"pkg/logger/logger.go": `package logger

type RedisLogger interface{ Redis() }

type LogBroadcaster struct{}

func NewLogBroadcaster() *LogBroadcaster { return &LogBroadcaster{} }

func (l *LogBroadcaster) Redis() {}

func NewLoggerWithBroadcaster(b *LogBroadcaster) *LogBroadcaster { return b }
`,
		"internal/biz/provider.go": `package biz

import "github.com/google/wire"

type Store interface{ Get() }

type store struct{}

func (s *store) Get() {}

func NewStore() *store { return &store{} }

var ProviderBizSet = wire.NewSet(
	NewStore,
	NewOther,
	// Interfaces are bound to their implementation below.
	wire.Bind(new(Store), new(*store)),
)

func NewOther() *Other { return &Other{} }

type Other struct{}
`,
		"cmd/app/wire.go": `//go:build wireinject
// +build wireinject

package main

import (
	"github.com/google/wire"

	"example.com/app/internal/biz"
	"example.com/app/pkg/logger"
)

func mainApp() (*App, func(), error) {
	panic(wire.Build(
		NewApp,
		logger.ProviderLoggerSet,
		biz.ProviderBizSet,
		wire.Bind(new(logger.RedisLogger), new(*logger.LogBroadcaster)),
	))
}

type App struct{}
`,
		"cmd/app/main.go": `package main

import "example.com/app/internal/cmd"

func main() {
	app, cleanup, err := mainApp()
	if err != nil {
		panic(err)
	}
	defer cleanup()
	_ = app
	cmd.Run()
}
`,
		"internal/cmd/run.go": `package cmd

func Run() {}
`,
		"cmd/app/wire_gen.go": "// Code generated by Wire. DO NOT EDIT.\n\npackage main\n",
	}
	for name, content := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
	}
	return root
}

func read(t *testing.T, root, name string) string {
	t.Helper()
	content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
	require.NoError(t, err)
	return string(content)
}

func TestConvertRewritesProviderSet(t *testing.T) {
	root := fixture(t)
	_, err := Convert(Options{Root: root, Apply: true, SkipVerify: true})
	require.NoError(t, err)

	got := read(t, root, "internal/biz/provider.go")
	assert.Contains(t, got, `"github.com/Xwudao/loom"`)
	assert.NotContains(t, got, "google/wire")
	// The binding replaces the plain entry for its constructor.
	assert.Contains(t, got, "loom.As[Store](NewStore)")
	assert.Contains(t, got, "loom.Provide(NewOther)")
	assert.NotContains(t, got, "wire.Bind")
	assert.Contains(t, got, "// Interfaces are bound to their implementation below.")
}

func TestConvertMovesGraphBindIntoModule(t *testing.T) {
	root := fixture(t)
	_, err := Convert(Options{Root: root, Apply: true, SkipVerify: true})
	require.NoError(t, err)

	// The graph-bound interface belongs next to the constructor that implements
	// it, and must lose the graph's package qualifier on the way.
	got := read(t, root, "pkg/logger/provider.go")
	assert.Contains(t, got, "loom.As[RedisLogger](NewLogBroadcaster)")
	assert.NotContains(t, got, "logger.RedisLogger")
}

func TestConvertReplacesInjectorWithGraph(t *testing.T) {
	root := fixture(t)
	result, err := Convert(Options{Root: root, Apply: true, SkipVerify: true})
	require.NoError(t, err)
	assert.Contains(t, result.Created, "cmd/app/graph.go")
	assert.Contains(t, result.Removed, "cmd/app/wire.go")
	assert.Contains(t, result.Removed, "cmd/app/wire_gen.go")

	got := read(t, root, "cmd/app/graph.go")
	assert.NotContains(t, got, "wireinject")
	assert.Contains(t, got, "//go:generate go tool loom generate .")
	assert.Contains(t, got, `mainAppGraph = loom.Graph[*App](`)
	assert.Contains(t, got, `loom.Name("mainApp")`)
	assert.Contains(t, got, "loom.Provide(NewApp)")
	// Modules stay modules; only constructors are wrapped.
	assert.Contains(t, got, "\t\tlogger.ProviderLoggerSet,")
	assert.Contains(t, got, "\t\tbiz.ProviderBizSet,")

	_, statErr := os.Stat(filepath.Join(root, "cmd", "app", "wire.go"))
	assert.True(t, os.IsNotExist(statErr), "wire.go should be removed")
}

func TestConvertRewritesCallSites(t *testing.T) {
	root := fixture(t)
	_, err := Convert(Options{Root: root, Apply: true, SkipVerify: true})
	require.NoError(t, err)

	got := read(t, root, "cmd/app/main.go")
	assert.Contains(t, got, "app, lifecycle, err := mainApp()")
	assert.Contains(t, got, "lifecycle.Stop(context.Background())")
	assert.Contains(t, got, `"context"`)
	assert.NotContains(t, got, "defer cleanup()")
}

func TestConvertPreservesVarDeclaration(t *testing.T) {
	root := fixture(t)
	path := filepath.Join(root, "internal", "cmd", "send.go")
	require.NoError(t, os.WriteFile(path, []byte(`package cmd

func Send() {
	var app, f, err = build()
	if err != nil {
		panic(err)
	}
	defer f()
	_ = app
}
`), 0o644))
	_, err := Convert(Options{Root: root, Apply: true, SkipVerify: true})
	require.NoError(t, err)

	got := read(t, root, "internal/cmd/send.go")
	// build() is not an injector, so the file is left alone.
	assert.Contains(t, got, "var app, f, err = build()")
}

func TestConvertIsTransactional(t *testing.T) {
	root := fixture(t)
	loggerBefore := read(t, root, "pkg/logger/provider.go")

	// A bind whose constructor is nowhere in the set cannot be converted, and
	// the project must be left exactly as it was.
	require.NoError(t, os.WriteFile(filepath.Join(root, "internal", "biz", "provider.go"),
		[]byte(`package biz

import "github.com/google/wire"

type Store interface{ Get() }

var ProviderBizSet = wire.NewSet(
	NewOther,
	wire.Bind(new(Store), new(*Missing)),
)

func NewOther() *Other { return &Other{} }

type Other struct{}
`), 0o644))

	_, err := Convert(Options{Root: root, Apply: true, SkipVerify: true})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "Missing")

	got := read(t, root, "internal/biz/provider.go")
	assert.Contains(t, got, "wire.NewSet")
	assert.Contains(t, got, "wire.Bind")
	assert.Equal(t, loggerBefore, read(t, root, "pkg/logger/provider.go"),
		"no unrelated file may change")
	// The graph files must not have been created either.
	_, statErr := os.Stat(filepath.Join(root, "cmd", "app", "graph.go"))
	assert.True(t, os.IsNotExist(statErr))
}

func TestConvertDryRunWritesNothing(t *testing.T) {
	root := fixture(t)
	before := read(t, root, "internal/biz/provider.go")
	result, err := Convert(Options{Root: root, Apply: false})
	require.NoError(t, err)
	assert.True(t, result.DryRun)
	assert.NotEmpty(t, result.Rewritten)
	assert.Equal(t, before, read(t, root, "internal/biz/provider.go"))
	_, statErr := os.Stat(filepath.Join(root, "cmd", "app", "graph.go"))
	assert.True(t, os.IsNotExist(statErr))
}

func TestConvertReportsLeftoverMentions(t *testing.T) {
	root := fixture(t)
	require.NoError(t, os.WriteFile(filepath.Join(root, "docs.md"),
		[]byte("Regenerate with `wire ./cmd/app`.\n"), 0o644))

	result, err := Convert(Options{Root: root, Apply: false})
	require.NoError(t, err)
	joined := strings.Join(result.Notes, "\n")
	assert.Contains(t, joined, "still mention Wire")
	assert.Contains(t, joined, "docs.md")
}

func TestTypeName(t *testing.T) {
	assert.Equal(t, "LogBroadcaster", typeName("*logger.LogBroadcaster"))
	assert.Equal(t, "store", typeName("*store"))
	assert.Equal(t, "RedisClient", typeName("data.RedisClient"))
}

func TestMatchesConstructor(t *testing.T) {
	// The entry is found from the bound type, in either spelling.
	assert.True(t, matchesConstructor("NewLogBroadcaster", "LogBroadcaster"))
	assert.True(t, matchesConstructor("logger.NewLogBroadcaster", "LogBroadcaster"))
	assert.True(t, matchesConstructor("NewStore", "store"))
	assert.True(t, matchesConstructor("newStore", "store"))
	assert.False(t, matchesConstructor("NewLogBroadcaster", "Logger"))
	assert.False(t, matchesConstructor("ProvideStore", "Store"))
}

func TestGraphVarName(t *testing.T) {
	assert.Equal(t, "mainAppGraph", graphVarName("mainApp"))
	assert.Equal(t, "migrateCmdGraph", graphVarName("MigrateCmd"))
	assert.Equal(t, "testAppGraph", graphVarName("TestApp"))
}

func TestIsModuleReference(t *testing.T) {
	registry := map[string]*setModel{
		"ProviderBizSet":    {},
		"ProviderConfigSet": {},
		"ProvideUtilSet":    {},
	}
	assert.True(t, isModuleReference("ProviderBizSet", registry))
	assert.True(t, isModuleReference("config.ProviderConfigSet", registry))
	// ProvideUtilSet is a set even though its name starts with "Provide".
	assert.True(t, isModuleReference("utils.ProvideUtilSet", registry))
	// ProvideStorageConfigLoader is a constructor despite its prefix.
	assert.False(t, isModuleReference("ProvideStorageConfigLoader", registry))
	assert.False(t, isModuleReference("NewUserBiz", registry))
	assert.False(t, isModuleReference("ai.NewOpenAICompat", registry))
	// A set from another module is still recognised by its name.
	assert.True(t, isModuleReference("shared.HTTPSet", registry))
}
